#!/usr/bin/env bash
# Sets up a custom 404 page in Nginx

# Install nginx if not installed
sudo apt-get update -y
sudo apt-get install -y nginx

# Create the custom 404 page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/error_404.html

# Update Nginx config only if error_page is NOT already added
if ! grep -q "error_page 404 /error_404.html;" /etc/nginx/sites-available/default; then
    sudo sed -i '/server_name _;/a \    error_page 404 /error_404.html;\n    location = /error_404.html {\n        root /var/www/html;\n        internal;\n    }' /etc/nginx/sites-available/default
fi

# Restart nginx
sudo service nginx restart

